#!/bin/bash
# Demo script to show the interactive prompt feature

clear
echo "════════════════════════════════════════════════════════════"
echo "  AIX Simulation - Interactive Prompt Demo"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "This demo shows the new interactive prompt feature!"
echo ""
echo "STEP 1: Normal Linux prompt looks like:"
echo "  $ pwd"
echo ""
echo "STEP 2: After sourcing the simulation:"
echo "  $ source ./aix_simulation.sh"
echo ""
echo "Your prompt will change to:"
echo "  [AIX-7.3] user@aix-server:/workspaces/AIX-Lab-Simulation$"
echo ""
echo "This makes it VERY clear you're in AIX simulation mode!"
echo ""
echo "STEP 3: Work with AIX commands:"
echo "  [AIX-7.3] user@aix-server:~$ lspv"
echo "  [AIX-7.3] user@aix-server:~$ df -g"
echo "  [AIX-7.3] user@aix-server:~$ oslevel -r"
echo ""
echo "STEP 4: Exit cleanly when done:"
echo "  [AIX-7.3] user@aix-server:~$ exit_aix"
echo ""
echo "Your original prompt is restored automatically!"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Ready to try? Run: source ./aix_simulation.sh"
echo ""
