#!/bin/bash
# Test script for the interactive natural language interface

echo "Testing AIXA Interactive Mode"
echo "=============================="
echo ""
echo "This demonstrates the new 'aixa' command that provides"
echo "an interactive natural language interface for AIX commands."
echo ""
echo "Features:"
echo "  ✅ Continuous conversation mode"
echo "  ✅ No need to type 'ask' each time"
echo "  ✅ Special commands: explain, history, clear, quit/exit"
echo "  ✅ Educational tips with each command"
echo "  ✅ Direct command execution"
echo ""
echo "Usage:"
echo "  1. Start simulation: source ./aix_simulation.sh"
echo "  2. Enter interactive mode: aixa"
echo "  3. Ask naturally: 'show disk space', 'check memory', etc."
echo "  4. Exit: Type 'quit' or 'exit'"
echo ""
echo "Example Session:"
echo "────────────────────────────────────────────────────────"
echo "$ aixa"
echo ""
echo "Query> show disk space"
echo "📚 Educational Info: Reports file system usage in GB"
echo "Command: df -g"
echo "[output shown]"
echo ""
echo "Query> check memory"
echo "📚 Educational Info: Shows global memory statistics"
echo "Command: svmon -G"
echo "[output shown]"
echo ""
echo "Query> explain lspv"
echo "📖 lspv - List Physical Volumes"
echo "[detailed help shown]"
echo ""
echo "Query> quit"
echo "👋 Goodbye!"
echo "────────────────────────────────────────────────────────"
echo ""
echo "Ready to try? Run: aixa"
echo ""
